name: Build Jekyll
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
jobs:
  build:
    # Job name is Greeting
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Jekyll Builder for GitHub Pages
        uses: meitar/jekyll-builder-for-github-pages-action@v1